### ISSUE TITLE
Binary 5x5 Solving game potential improvements/to-do

### ISSUE THREAD

**Issue by tuckergol** [tuckergol/binarylogicrepo#3]
- [ ] Make thorough instructions for the game
- [x] Format better; change colors from red and blue to match theme and visualize binary better, fix resolution, format given numbers next to each row to stay consistent with game instructions
- [x] Delete consistently-updating output decimals to make the game effective for learning **(add "Submit" button instead for answers + output printing how many out of 4 they got correct)**
- [x] "New" button (randomly generate new given decimals to convert and also reset board to 0s--default) and "Submit" button
